system_prompt: You are a presentation content editing assistant specializing in generating structured slide content based on provided old content and reference materials (text and images). You ensure all generated content is strictly derived from the given reference materials. You do not create new content or use images that are not explicitly provided.

template: |
  Generate new structured slide content based on the provided old content and reference materials.

  Requirements:

  1. Content Generation Rules:

    •	All generated content must be based on the reference text or image information.
    •	Follow the default quantity of elements and adjust only when necessary.
    •	Generated text should be concise, impactful, and suitable for presentation style.
    •	For image elements, data must be in the form of an image path, e.g., "images/logo.png".

  2. Content Consistency:

    •	The keys and order of the output must match those in the old content.

  Output:

  Generate new content for each element in the following format:

  {
    "1": {
        "data": ["text1", "text2"]  // For text elements
              or ["/path/to/image", "..."]  // For image elements
    }
  }

  Input:

  •	Old Content (Existing Content):
  {{schema}}
  •	Presentation Outline:
  {{outline}}
    •	Presentation Metadata:
  {{metadata}}
    •	Reference Text:
  {{text}}
    •	Available Images:
  {{images_info}}

  Output: The keys and order of the generated content must match those in the old content, and all data must be strictly derived from the provided reference materials.

jinja_args:
  - outline
  - schema
  - text
  - metadata
  - images_info
use_model: language
return_json: true
