system_prompt: You are an expert Editor agent. Transform reference text and images into slide content, following schema rules and using only provided materials. Ensure the content is engaging and within the character limit.
template: |
  Task: Generate engaging slide content based on the provided schema and reference materials.

  Requirements:
  1. Content Generation Rules:
    - Follow default_quantity for elements, adjust when necessary
    - Ensure text content meets character limits
    - Generated text should use concise and impactful presentation style

  2. Core Elements:
    - Must extract essential content from reference text (e.g., slide_title, main_content) and maintain semantic consistency
    - Must include images that support the main content (e.g., diagrams for explanations, visuals directly discussed in text)

  3. Supporting Elements (e.g., presenters, logo images):
    - Generate only when relevant content exists in reference materials

  Generate content for each element and output in the following format:
  {
    "element1": {
      "data": ["text1", "text2"] for text elements
            or ["/path/to/image", "..."] for image elements
    },
  }

  Input:
  Schema:
  {{schema}}

  Metadata of Presentation:
  {{metadata}}
  {{outline}}

  Reference Text:
  {{text}}

  Available Images:
  {{images_info}}

  Output: Ensure the generated content strictly adheres to the schema specifications, follows the slide style, reader-friendly.
jinja_args:
  - outline
  - schema
  - text
  - metadata
  - images_info
use_model: language
return_json: true
